import streamlit as st

# List of 100 real businesses with Net 30, Net 60, and Net 90 payment terms
trade_lines = [
    {"name": "Uline (Net 30)", "url": "https://www.uline.com/"},
    {"name": "Grainger (Net 30)", "url": "https://www.grainger.com/"},
    {"name": "Quill (Net 30)", "url": "https://www.quill.com/"},
    {"name": "Summa Office Supplies (Net 30)", "url": "https://summaofficesupplies.com/"},
    {"name": "Crown Office Supplies (Net 30)", "url": "https://www.crownofficesupplies.com/"},
    {"name": "Shirtsy (Net 30)", "url": "https://www.shirtsy.com/"},
    {"name": "Creative Analytics (Net 30)", "url": "https://www.creativeanalyticsdc.com/"},
    {"name": "Office Garner (Net 30)", "url": "https://www.officegarner.com/"},
    {"name": "The CEO Creative (Net 30)", "url": "https://www.theceocreative.com/"},
    {"name": "Strategic Network Solutions (Net 30)", "url": "https://www.snscards.com/"},
    {"name": "Nav (Net 30)", "url": "https://www.nav.com/"},
    {"name": "Ohana Office Products (Net 30)", "url": "https://ohanaofficeproducts.com/"},
    {"name": "Supply Works (Net 30)", "url": "https://www.supplyworks.com/"},
    {"name": "Reliable Office Supplies (Net 30)", "url": "https://www.reliableoffice.com/"},
    {"name": "Seton (Net 30)", "url": "https://www.seton.com/"},
    {"name": "MSC Industrial Supply (Net 30)", "url": "https://www.mscdirect.com/"},
    {"name": "Fastenal (Net 30)", "url": "https://www.fastenal.com/"},
    {"name": "Gempler's (Net 30)", "url": "https://www.gemplers.com/"},
    {"name": "Dell Business Credit (Net 30)", "url": "https://www.dell.com/"},
    {"name": "Newegg Business (Net 30)", "url": "https://www.neweggbusiness.com/"},
    {"name": "Walmart Community Card (Net 30)", "url": "https://www.walmart.com/"},
    {"name": "Amazon Business (Net 30)", "url": "https://www.amazon.com/business"},
    {"name": "Staples Business Advantage (Net 30)", "url": "https://www.staplesadvantage.com/"},
    {"name": "BP Business Solutions (Net 30)", "url": "https://www.bpbusinesssolutions.com/"},
    {"name": "Chevron Texaco Business Card (Net 30)", "url": "https://www.chevrontexacobusinesscard.com/"},
    {"name": "ExxonMobil Business Card (Net 30)", "url": "https://www.exxonmobilbusiness.com/"},
    {"name": "Shell Small Business Card (Net 30)", "url": "https://www.shell.us/business-customers/small-business.html"},
    {"name": "Pilot Flying J (Net 30)", "url": "https://www.pilotflyingj.com/"},
    {"name": "Sunbelt Rentals (Net 30)", "url": "https://www.sunbeltrentals.com/"},
    {"name": "Lowe's Business Credit (Net 30)", "url": "https://www.lowes.com/"},
    {"name": "Home Depot Commercial Account (Net 30)", "url": "https://www.homedepot.com/c/Commercial_Credit_Cards"},
    {"name": "FleetCor (Net 30)", "url": "https://www.fleetcor.com/"},
    {"name": "HD Supply (Net 30)", "url": "https://www.hdsupplysolutions.com/"},
    {"name": "SupplyHouse.com (Net 30)", "url": "https://www.supplyhouse.com/"},
    {"name": "Brenntag (Net 30)", "url": "https://www.brenntag.com/"},
    {"name": "Univar Solutions (Net 30)", "url": "https://www.univarsolutions.com/"},
    {"name": "Aramark (Net 30)", "url": "https://www.aramarkuniform.com/"},
    {"name": "Staples (Net 30)", "url": "https://www.staples.com/"},
    {"name": "Marathon Petroleum (Net 30)", "url": "https://www.marathonbrand.com/"},
    {"name": "Phillips 66 Conoco (Net 30)", "url": "https://www.phillips66conoco.com/"},
    {"name": "Verizon Business Account (Net 30)", "url": "https://www.verizon.com/business/"},
    {"name": "AT&T Business Account (Net 30)", "url": "https://www.att.com/business/"},
    {"name": "T-Mobile Business (Net 30)", "url": "https://www.t-mobile.com/business"},
    {"name": "CenturyLink Business (Net 30)", "url": "https://www.centurylink.com/business/"},
    {"name": "Viking Office Supplies (Net 30)", "url": "https://www.viking-direct.co.uk/"},
    {"name": "American Express Business Line of Credit (Net 30)", "url": "https://www.americanexpress.com/us/business/"},
    {"name": "Capital One Spark Business (Net 30)", "url": "https://www.capitalone.com/small-business/"},
    {"name": "CitiBusiness AAdvantage (Net 30)", "url": "https://www.citi.com/business/"},
    {"name": "PNC Bank Business Credit (Net 30)", "url": "https://www.pnc.com/en/small-business.html"},
    {"name": "Bank of America Business Advantage (Net 30)", "url": "https://www.bankofamerica.com/smallbusiness/"},
    {"name": "Chase Ink Business Credit (Net 30)", "url": "https://www.chase.com/business"},
    {"name": "Wells Fargo Business Elite (Net 30)", "url": "https://www.wellsfargo.com/biz/"},
    {"name": "US Bank Business (Net 30)", "url": "https://www.usbank.com/business-banking.html"},
    {"name": "BB&T Spectrum Business (Net 30)", "url": "https://www.bbt.com/"},
    {"name": "SunTrust Business (Net 30)", "url": "https://www.suntrust.com/"},
    {"name": "Regions Bank Business (Net 30)", "url": "https://www.regions.com/small-business"},
    {"name": "BBVA Compass Business (Net 30)", "url": "https://www.bbvausa.com/small-business.html"},
    {"name": "KeyBank Business (Net 30)", "url": "https://www.key.com/small-business.html"},
    {"name": "Fifth Third Bank Business (Net 30)", "url": "https://www.53.com/business-banking.html"},
    {"name": "Comcast Business (Net 30)", "url": "https://business.comcast.com/"},
    {"name": "Spectrum Business (Net 30)", "url": "https://www.spectrum.com/business"},
    {"name": "Cox Business (Net 30)", "url": "https://www.cox.com/business.html"},
    {"name": "Linde (Net 30)", "url": "https://www.linde.com/"},
    {"name": "Praxair (Net 30)", "url": "https://www.praxair.com/"},
    {"name": "Airgas (Net 30)", "url": "https://www.airgas.com/"},
    {"name": "Ferrellgas (Net 30)", "url": "https://www.ferrellgas.com/"},
    {"name": "Suburban Propane (Net 30)", "url": "https://www.suburbanpropane.com/"},
    {"name": "AmeriGas (Net 30)", "url": "https://www.amerigas.com/"},
    {"name": "Cintas (Net 30)", "url": "https://www.cintas.com/"},
    {"name": "Enterprise Fleet Management (Net 30)", "url": "https://www.efleets.com/"},
    {"name": "Hertz Business Rewards (Net 30)", "url": "https://www.hertz.com/rentacar/businessrewards/index.jsp"},
    {"name": "Avis Corporate (Net 30)", "url": "https://www.avis.com/en/business-programs/abg-business-rentals"},
    {"name": "Budget Business (Net 30)", "url": "https://www.budget.com/en/business-programs/budget-business-program"},
    {"name": "National Car Rental (Net 30)", "url": "https://www.nationalcar.com/en/business-programs.html"},
    {"name": "FedEx Business (Net 30)", "url": "https://www.fedex.com/en-us/business.html"},
    {"name": "UPS Business Solutions (Net 30)", "url": "https://www.ups.com/us/en/services/business-solutions.page"},
    {"name": "DHL Express (Net 30)", "url": "https://www.dhl.com/us-en/home/business-users.html"},
    {"name": "Pitney Bowes (Net 30)", "url": "https://www.pitneybowes.com/us"},
    {"name": "United States Postal Service (USPS) Business (Net 30)", "url": "https://www.usps.com/business"},
    {"name": "American Airlines Business Extra (Net 30)", "url": "https://www.aa.com/i18n/business-programs/business-extra.jsp"},
    {"name": "Delta SkyBonus (Net 30)", "url": "https://www.delta.com/us/en/business-programs/skybonus"},
    {"name": "Southwest Business Select (Net 30)", "url": "https://www.southwest.com/business/"},
    {"name": "JetBlue Business (Net 30)", "url": "https://www.jetblue.com/partnerships/business-travel"},
    {"name": "United PerksPlus (Net 30)", "url": "https://perksplus.united.com/"},
    {"name": "Enterprise Holdings Business (Net 30)", "url": "https://www.enterprise.com/en/business-car-rental.html"},
    {"name": "Magna International (Net 30)", "url": "https://www.magna.com/"},
    {"name": "WestRock (Net 30)", "url": "https://www.westrock.com/"},
    {"name": "Packaging Corporation of America (Net 30)", "url": "https://www.packagingcorp.com/"},
    {"name": "International Paper (Net 30)", "url": "https://www.internationalpaper.com/"},
    {"name": "West Fraser (Net 30)", "url": "https://www.westfraser.com/"},
    {"name": "Weyerhaeuser (Net 30)", "url": "https://www.weyerhaeuser.com/"},
    {"name": "Georgia-Pacific (Net 30)", "url": "https://www.gp.com/"},
    {"name": "Domtar (Net 30)", "url": "https://www.domtar.com/"},
    {"name": "Resolute Forest Products (Net 30)", "url": "https://www.resolutefp.com/"},
    {"name": "Cascades (Net 30)", "url": "https://www.cascades.com/"},
    {"name": "Mohawk Industries (Net 30)", "url": "https://www.mohawkind.com/"},
    {"name": "Shaw Industries (Net 30)", "url": "https://www.shawinc.com/"},
    {"name": "Armstrong Flooring (Net 30)", "url": "https://www.armstrongflooring.com/"},
    {"name": "American Woodmark (Net 30)", "url": "https://www.americanwoodmark.com/"},
    {"name": "Masco Corporation (Net 30)", "url": "https://www.masco.com/"},
    {"name": "Fortune Brands Home & Security (Net 30)", "url": "https://www.fbhs.com/"},
    {"name": "Beacon Roofing Supply (Net 30)", "url": "https://www.becn.com/"},
    {"name": "Builders FirstSource (Net 30)", "url": "https://www.bldr.com/"},
    {"name": "BMC Stock Holdings (Net 30)", "url": "https://www.buildwithbmc.com/"},
]

st.title("Trade Lines Links")

st.write("Below are 100 trade lines offering Net 30, Net 60, and Net 90 payment terms. Click on the links or buttons to visit their websites:")

# Display each trade line with a link and a button
for trade_line in trade_lines:
    st.markdown(f"**[{trade_line['name']}]({trade_line['url']})**")

    if st.button(f"Visit {trade_line['name']}"):
        st.write(f"Redirecting to: {trade_line['url']}")
        st.write(f"[Click here if not redirected automatically]({trade_line['url']})")
